# Generated by Django 3.1.6 on 2021-07-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210708_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_img',
            name='image',
            field=models.ImageField(default=0, upload_to='Design_Img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=0, upload_to='Profile_Img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_img',
            name='image',
            field=models.ImageField(upload_to='Product_Img'),
        ),
    ]
