# Generated by Django 3.1.6 on 2021-07-10 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='mobil_no',
            new_name='contact_no',
        ),
    ]
