# Generated by Django 3.1.6 on 2021-07-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_size_p_in_seam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='p_Hips',
        ),
        migrations.AlterField(
            model_name='size',
            name='p_Crotch_Or_Rise',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='p_In_Seam',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='p_Knee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='p_Leg_Opening',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='p_Thigh',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='p_Waist',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='p_length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='s_Bicep_Loose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='s_Chest',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='s_Front_Chest',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='s_Front_Hips',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='s_Front_Stomach',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='s_Neck',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='s_Overarm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='s_Shirt_lenght',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='s_Shoulders',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='s_Sleeve_Length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='s_Waistcoat_Length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='s_Wrist',
            field=models.FloatField(),
        ),
    ]
