# Generated by Django 3.1.6 on 2021-07-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_size_p_hips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_detail',
            old_name='design',
            new_name='best_for',
        ),
        migrations.RenameField(
            model_name='product_detail',
            old_name='specify_for',
            new_name='design_pattern',
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='Specification',
            field=models.TextField(),
        ),
    ]
