# Generated by Django 3.1.6 on 2021-07-11 07:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210711_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Design Name'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Produc Price'),
        ),
    ]
