# Generated by Django 3.1.6 on 2021-07-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210711_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='thumbnail_image',
            field=models.ImageField(default=None, null=True, upload_to='Thumbnail Image'),
        ),
        migrations.AlterField(
            model_name='design_img',
            name='image',
            field=models.ImageField(upload_to='Design_Img', verbose_name='Design Image'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product_img',
            name='image',
            field=models.ImageField(upload_to='Product_Img', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Contact No'),
        ),
    ]
