# Generated by Django 3.1.6 on 2021-07-12 18:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210712_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Design Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='type',
            field=models.CharField(default=0, max_length=150, verbose_name='Design Type'),
            preserve_default=False,
        ),
    ]
