# Generated by Django 3.1.6 on 2021-07-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20210712_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='Design_Img', verbose_name='Thumbnail Image'),
        ),
    ]
