# Generated by Django 3.1.6 on 2021-07-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_design_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='id',
            field=models.SlugField(blank=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product_img',
            name='id',
            field=models.SlugField(blank=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
