# Generated by Django 3.1.6 on 2021-07-13 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20210713_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.product_detail'),
        ),
    ]
