# Generated by Django 3.1.6 on 2021-07-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_design_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='product',
        ),
        migrations.AddField(
            model_name='design',
            name='product',
            field=models.ManyToManyField(null=True, to='main_app.Product_detail'),
        ),
    ]
