# Generated by Django 3.1.6 on 2021-07-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20210713_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='product',
            field=models.ManyToManyField(to='main_app.Product_detail'),
        ),
    ]
