# Generated by Django 3.1.6 on 2021-07-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20210713_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='specification',
            field=models.CharField(max_length=200, null=True, verbose_name='Specification'),
        ),
    ]
