# Generated by Django 3.1.6 on 2021-07-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_design_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_cost', models.CharField(max_length=20)),
                ('user_id', models.IntegerField(default=1)),
                ('design_id', models.IntegerField(default=1)),
                ('prod_quantity', models.IntegerField(default=1)),
                ('prod_amount', models.FloatField(default=0)),
                ('design_amount', models.FloatField(default=0)),
            ],
        ),
    ]
