# Generated by Django 3.1.6 on 2021-07-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_mycart'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='product_id',
            field=models.IntegerField(default=1),
        ),
    ]
