# Generated by Django 3.1.6 on 2021-07-14 07:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_mycart_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oreder_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('contact_no', models.IntegerField()),
                ('pin_code', models.IntegerField()),
                ('state', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=150)),
                ('house_no', models.TextField()),
                ('area_landmark', models.TextField()),
                ('pro_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('Pro_price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Produc Price')),
                ('Product_quantity', models.IntegerField()),
                ('design_name', models.CharField(max_length=100)),
                ('design_price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Produc Price')),
                ('order_status', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Produc Price')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
