# Generated by Django 3.1.6 on 2021-07-16 05:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_oreder_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oreder_detail',
            name='area_landmark',
        ),
        migrations.RemoveField(
            model_name='oreder_detail',
            name='city',
        ),
        migrations.RemoveField(
            model_name='oreder_detail',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='oreder_detail',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='oreder_detail',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='oreder_detail',
            name='state',
        ),
        migrations.AddField(
            model_name='mycart',
            name='totalamount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='oreder_detail',
            name='Product_Id',
            field=models.IntegerField(null=True, verbose_name='Product Id'),
        ),
        migrations.AddField(
            model_name='oreder_detail',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='oreder_detail',
            name='address_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='oreder_detail',
            name='design_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oreder_detail',
            name='size_detail',
            field=models.TextField(null=True, verbose_name='Size Detail'),
        ),
        migrations.AddField(
            model_name='oreder_detail',
            name='size_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oreder_detail',
            name='size_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='oreder_detail',
            name='Pro_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Produc Price'),
        ),
        migrations.AlterField(
            model_name='oreder_detail',
            name='Product_quantity',
            field=models.IntegerField(null=True, verbose_name='Product Quantity'),
        ),
        migrations.AlterField(
            model_name='oreder_detail',
            name='design_name',
            field=models.CharField(max_length=100, verbose_name='Design Name'),
        ),
        migrations.AlterField(
            model_name='oreder_detail',
            name='design_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Produc Price'),
        ),
        migrations.AlterField(
            model_name='oreder_detail',
            name='order_status',
            field=models.CharField(max_length=100, null=True, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='oreder_detail',
            name='pro_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='oreder_detail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Produc Price'),
        ),
        migrations.AlterField(
            model_name='oreder_detail',
            name='user_name',
            field=models.CharField(max_length=200, null=True, verbose_name='User Name'),
        ),
    ]
