# Generated by Django 3.1.6 on 2021-07-16 07:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20210716_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Discount On Project in'),
        ),
    ]
