# Generated by Django 3.1.6 on 2021-07-16 08:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_product_detail_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Aftr discount Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Product Price'),
        ),
    ]
