# Generated by Django 3.1.6 on 2021-07-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_auto_20210716_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='discount',
            field=models.IntegerField(null=True, verbose_name='Discount On Product in "%"'),
        ),
    ]
