# Generated by Django 3.1.6 on 2021-07-16 10:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_auto_20210716_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='new_price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Aftr discount Price'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Product Price'),
        ),
    ]
