# Generated by Django 3.1.6 on 2021-07-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_auto_20210716_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('product_id', models.IntegerField(null=True)),
                ('design_id', models.IntegerField(null=True)),
            ],
        ),
    ]
