# Generated by Django 3.1.6 on 2021-07-17 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.product_detail'),
        ),
    ]
