# Generated by Django 3.1.6 on 2021-07-18 09:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_wishlist_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oreder_detail',
            name='design_id',
        ),
        migrations.RemoveField(
            model_name='oreder_detail',
            name='design_name',
        ),
        migrations.RemoveField(
            model_name='oreder_detail',
            name='design_price',
        ),
        migrations.AlterField(
            model_name='oreder_detail',
            name='Pro_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='oreder_detail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total Product~ Price'),
        ),
    ]
