# Generated by Django 3.1.6 on 2021-07-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_auto_20210718_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Femail_size_Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gown_length', models.FloatField()),
                ('upper_Chest', models.FloatField()),
                ('chest', models.FloatField()),
                ('waist', models.FloatField()),
                ('upeer_waist', models.FloatField()),
                ('stomach', models.FloatField()),
                ('hips', models.FloatField()),
                ('shoulder', models.FloatField()),
                ('front_neck_depth', models.FloatField()),
                ('back_neck_depth', models.FloatField()),
                ('neck_to_solider', models.FloatField()),
                ('sleeve_length', models.FloatField()),
                ('sleev_round', models.FloatField()),
                ('around_bust', models.FloatField()),
                ('blouse_length', models.FloatField()),
                ('arm_hole', models.FloatField()),
                ('around_arms', models.FloatField()),
                ('waist_to_ankel_length', models.FloatField()),
                ('full_body_lenght', models.FloatField()),
                ('dress_length', models.FloatField()),
                ('neck_line', models.FloatField()),
                ('upper_bust', models.FloatField()),
                ('chest_bust', models.FloatField()),
                ('thigh', models.FloatField()),
                ('knee', models.FloatField()),
                ('calf', models.FloatField(verbose_name='Calf/Ankel')),
                ('shoulder_full_lenght', models.FloatField()),
                ('fron_neck_depth', models.FloatField()),
            ],
        ),
    ]
