# Generated by Django 3.1.6 on 2021-07-18 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0039_femail_size_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='femail_size_chart',
            name='dress_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='femail_size_chart',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='femail_size_chart',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='femail_size_chart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
