# Generated by Django 3.1.6 on 2021-07-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_auto_20210718_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='femail_size_chart',
            old_name='around_arms',
            new_name='sleev_around',
        ),
        migrations.RenameField(
            model_name='femail_size_chart',
            old_name='fron_neck_depth',
            new_name='upper_waist',
        ),
        migrations.RemoveField(
            model_name='femail_size_chart',
            name='sleev_round',
        ),
        migrations.RemoveField(
            model_name='femail_size_chart',
            name='upeer_waist',
        ),
        migrations.RemoveField(
            model_name='femail_size_chart',
            name='upper_Chest',
        ),
        migrations.AddField(
            model_name='femail_size_chart',
            name='ankel_hem',
            field=models.FloatField(null=True, verbose_name='Ankel Hem'),
        ),
        migrations.AlterField(
            model_name='femail_size_chart',
            name='chest',
            field=models.FloatField(verbose_name='Chest(Around)'),
        ),
        migrations.AlterField(
            model_name='femail_size_chart',
            name='waist',
            field=models.FloatField(verbose_name='Waist(Around)'),
        ),
    ]
