# Generated by Django 3.1.6 on 2021-07-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_auto_20210719_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='femail_size_chart',
            name='upper_chest',
            field=models.FloatField(null=True),
        ),
    ]
