# Generated by Django 3.1.6 on 2021-07-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_oreder_detail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='oreder_detail',
            name='review',
            field=models.BooleanField(default=False),
        ),
    ]
