# Generated by Django 3.1.6 on 2021-07-20 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0044_oreder_detail_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stiching_quality', models.IntegerField()),
                ('product_quality', models.IntegerField()),
                ('fitting_quality', models.IntegerField()),
                ('liked', models.IntegerField()),
                ('message', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
