# Generated by Django 3.1.6 on 2021-07-20 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_user_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_feedback',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.product_detail'),
        ),
    ]
