# Generated by Django 3.1.6 on 2021-07-20 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0047_oreder_detail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('p_length', models.FloatField()),
                ('p_Waist', models.FloatField()),
                ('p_Hips', models.FloatField()),
                ('p_Thigh', models.FloatField()),
                ('p_Knee', models.FloatField()),
                ('p_Leg_Opening', models.FloatField()),
                ('p_Crotch_Or_Rise', models.FloatField()),
                ('p_In_Seam', models.FloatField()),
                ('s_Shirt_lenght', models.FloatField()),
                ('s_Sleeve_Length', models.FloatField()),
                ('s_Shoulders', models.FloatField()),
                ('s_Chest', models.FloatField()),
                ('s_Overarm', models.FloatField()),
                ('s_Waistcoat_Length', models.FloatField()),
                ('s_Bicep_Loose', models.FloatField()),
                ('s_Front_Chest', models.FloatField()),
                ('s_Front_Stomach', models.FloatField()),
                ('s_Front_Hips', models.FloatField()),
                ('s_Wrist', models.FloatField()),
                ('s_Neck', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='oreder_detail',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Delivered Or Not'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
