# Generated by Django 3.1.6 on 2021-07-21 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0048_auto_20210720_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_feedback',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.oreder_detail'),
        ),
    ]
