# Generated by Django 3.1.6 on 2021-07-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0049_user_feedback_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='total_num',
            field=models.IntegerField(null=True, verbose_name='Total Product'),
        ),
    ]
