# Generated by Django 3.1.6 on 2021-07-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0050_product_detail_total_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_feedback',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
