# Generated by Django 3.2.5 on 2021-07-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0051_user_feedback_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact_no',
            field=models.CharField(max_length=20),
        ),
    ]
