# Generated by Django 3.2.6 on 2021-08-15 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0052_alter_address_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='size_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Size Detail')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('design_type', models.CharField(max_length=50, verbose_name='Design Type Of clothes')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='blouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulders', models.FloatField()),
                ('shouldersfull_lenght', models.FloatField()),
                ('front_neck_depth', models.FloatField()),
                ('chest_around', models.FloatField()),
                ('waist_around', models.FloatField()),
                ('back_neck_depth', models.FloatField()),
                ('blouse_length', models.FloatField()),
                ('sleeve_length', models.FloatField()),
                ('sleeve_around', models.FloatField()),
                ('armhole_around', models.FloatField()),
                ('size_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.size_detail')),
            ],
        ),
    ]
