# Generated by Django 3.2.6 on 2021-08-16 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0054_size_detail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='kurti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_length', models.FloatField()),
                ('sleev_length', models.FloatField()),
                ('neckline', models.FloatField()),
                ('upper_bust', models.FloatField()),
                ('chest_bust', models.FloatField()),
                ('stomach', models.FloatField()),
                ('hip', models.FloatField()),
                ('shoulder', models.FloatField()),
                ('arm_hole', models.FloatField()),
                ('waist', models.FloatField()),
                ('thigh', models.FloatField()),
                ('knee', models.FloatField()),
                ('calf', models.FloatField()),
                ('ankel_hem', models.FloatField()),
                ('size_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.size_detail')),
            ],
        ),
    ]
