# Generated by Django 3.2.6 on 2021-08-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0055_kurti'),
    ]

    operations = [
        migrations.CreateModel(
            name='for_lahenga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_neck_depth', models.FloatField()),
                ('around_bust', models.FloatField()),
                ('neck_to_soloulder', models.FloatField()),
                ('upper_waist', models.FloatField()),
                ('blouse_length', models.FloatField()),
                ('shoulder', models.FloatField()),
                ('back_neck_depth', models.FloatField()),
                ('around_armholes', models.FloatField()),
                ('sleeve_length', models.FloatField()),
                ('waist', models.FloatField()),
                ('hips', models.FloatField()),
                ('waist_to_ankel', models.FloatField()),
                ('full_body', models.FloatField()),
                ('size_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.size_detail')),
            ],
        ),
        migrations.CreateModel(
            name='for_gown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gown_length', models.FloatField()),
                ('upper_chest', models.FloatField()),
                ('chest', models.FloatField()),
                ('waist', models.FloatField()),
                ('stomach', models.FloatField()),
                ('hips', models.FloatField()),
                ('shoulder', models.FloatField()),
                ('front_neck_depth', models.FloatField()),
                ('sleeve_length', models.FloatField()),
                ('sleeve_round', models.FloatField()),
                ('arm_hole', models.FloatField()),
                ('size_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.size_detail')),
            ],
        ),
    ]
