# Generated by Django 3.2.6 on 2021-08-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_for_gown_for_lahenga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='for_lahenga',
            old_name='neck_to_soloulder',
            new_name='neck_to_shoulder',
        ),
    ]
