# Generated by Django 3.2.6 on 2021-08-17 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0057_rename_neck_to_soloulder_for_lahenga_neck_to_shoulder'),
    ]

    operations = [
        migrations.CreateModel(
            name='male_pantshirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_length', models.FloatField()),
                ('p_Waist', models.FloatField()),
                ('p_Hips', models.FloatField()),
                ('p_Thigh', models.FloatField()),
                ('p_Knee', models.FloatField()),
                ('p_Leg_Opening', models.FloatField()),
                ('p_Crotch_Or_Rise', models.FloatField()),
                ('p_In_Seam', models.FloatField()),
                ('s_Shirt_lenght', models.FloatField()),
                ('s_Sleeve_Length', models.FloatField()),
                ('s_Shoulders', models.FloatField()),
                ('s_Chest', models.FloatField()),
                ('s_Overarm', models.FloatField()),
                ('s_Waistcoat_Length', models.FloatField()),
                ('s_Bicep_Loose', models.FloatField()),
                ('s_Front_Chest', models.FloatField()),
                ('s_Front_Stomach', models.FloatField()),
                ('s_Front_Hips', models.FloatField()),
                ('s_Wrist', models.FloatField()),
                ('s_Neck', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('size_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.size_detail')),
            ],
        ),
        migrations.DeleteModel(
            name='MailSize',
        ),
    ]
