# Generated by Django 3.2.6 on 2021-08-31 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0058_auto_20210817_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='download_through',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='referal',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Offer Name')),
                ('img', models.ImageField(upload_to='Offers_image', verbose_name='Offer Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
