# Generated by Django 3.2.6 on 2021-09-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0059_auto_20210831_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='download_through',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referal',
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
