# Generated by Django 3.1.6 on 2021-09-11 07:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0061_auto_20210906_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='oreder_detail',
            name='refral_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oreder_detail',
            name='Pro_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Aftr discount Price'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Product Price'),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_referral_id', models.CharField(max_length=150, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('referral_id', models.CharField(max_length=150, null=True)),
                ('share_by', models.IntegerField(null=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('total_active_coin', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('used_time', models.IntegerField(default=0)),
                ('user', models.OneToOneField(default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_detail', models.IntegerField(null=True)),
                ('order_detail', models.IntegerField(null=True)),
                ('total_order', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bonus_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bonus_on_product', models.CharField(default='', max_length=10, verbose_name='Bonus On Product in (%)')),
                ('date_of_order', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_of_delivery', models.DateTimeField(null=True)),
                ('bonus_referr_to', models.IntegerField(null=True)),
                ('delivery_status', models.BooleanField(default=False)),
                ('is_added', models.BooleanField(default=False)),
                ('total_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('user', models.ForeignKey(default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
