# Generated by Django 3.2.8 on 2022-01-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0062_auto_20210911_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
